// Workout //

// Workout一覧取得
export const GET_WORKOUT_SUCCESS = "GET_WORKOUT_SUCCESS"
export const GET_WORKOUT_FAIL = "GET_WORKOUT_FAIL"

// ブログ詳細取得
export const GET_WORKOUT_DETAIL_SUCCESS = "GET_WORKOUT_DETAIL_SUCCESS"
export const GET_WORKOUT_DETAIL_FAIL = "GET_WORKOUT_DETAIL_FAIL"

// 読み込み中
export const SET_WORKOUT_LOADING = "SET_WORKOUT_LOADING"
export const REMOVE_WORKOUT_LOADING = "REMOVE_WORKOUT_LOADING"

// Target

// Target一覧取得
export const GET_TARGET_SUCCESS = "GET_TARGET_SUCCESS"
export const GET_TARGET_FAIL = "GET_TARGET_FAIL"

// 読み込み中
export const SET_TARGET_LOADING = "SET_TARGET_LOADING"
export const REMOVE_TARGET_LOADING = "REMOVE_TARGET_LOADING"

// Exercise

// Exercise一覧取得
export const GET_EXERCISE_SUCCESS = "GET_EXERCISE_SUCCESS"
export const GET_EXERCISE_FAIL = "GET_EXERCISE_FAIL"

// 読み込み中
export const SET_EXERCISE_LOADING = "GET_EXERCISE_LOADING"
export const REMOVE_EXERCISE_LOADING = "REMOVE_EXERCISE_LOADING"